/**
 * Generate a unified wallet: one private key -> EVM + Kaspa addresses.
 *
 * - EVM address works on Ethereum, Base, Igra, and all EVM chains
 * - Kaspa address uses the same secp256k1 key with x-only pubkey (schnorr)
 *
 * Saves key to .env, prints only addresses.
 *
 * Usage: node generate-wallet.js
 */

const { ethers } = require("ethers");
const fs = require("fs");
const path = require("path");

// ── Kaspa bech32 encoding ────────────────────────────────────────────
// Kaspa uses BCH-style 40-bit polymod (NOT standard bech32 30-bit).
// Source: rusty-kaspa/crypto/addresses/src/bech32.rs

const CHARSET = "qpzry9x8gf2tvdw0s3jn54khce6mua7l";

// 40-bit polymod with Kaspa's generator constants
function polymod(values) {
  let c = 1n;
  for (const d of values) {
    const c0 = c >> 35n;
    c = ((c & 0x07ffffffffn) << 5n) ^ BigInt(d);
    if (c0 & 0x01n) c ^= 0x98f2bc8e61n;
    if (c0 & 0x02n) c ^= 0x79b76d99e2n;
    if (c0 & 0x04n) c ^= 0xf33e5fb3c4n;
    if (c0 & 0x08n) c ^= 0xae2eabe2a8n;
    if (c0 & 0x10n) c ^= 0x1e4f43e470n;
  }
  return c ^ 1n;
}

// Convert 8-bit array to 5-bit array with right padding
function conv8to5(data) {
  const result = [];
  let buff = 0, bits = 0;
  for (const byte of data) {
    buff = (buff << 8) | byte;
    bits += 8;
    while (bits >= 5) {
      bits -= 5;
      result.push((buff >> bits) & 0x1f);
      buff &= (1 << bits) - 1;
    }
  }
  if (bits > 0) {
    result.push((buff << (5 - bits)) & 0x1f);
  }
  return result;
}

function kaspaAddressEncode(prefix, version, payload) {
  // 5-bit encode: [version_byte, ...payload_bytes]
  const fivebitPayload = conv8to5([version, ...payload]);

  // 5-bit prefix: each byte of prefix string AND 0x1f
  const fivebitPrefix = [...prefix].map(c => c.charCodeAt(0) & 0x1f);

  // Checksum input: fivebitPrefix + [0] + fivebitPayload + [0,0,0,0,0,0,0,0]
  const checksumInput = [...fivebitPrefix, 0, ...fivebitPayload, 0, 0, 0, 0, 0, 0, 0, 0];
  const checksumVal = polymod(checksumInput);

  // Checksum is 40 bits -> convert to 5-bit via conv8to5 on the last 5 bytes
  const checksumBytes = [];
  for (let i = 4; i >= 0; i--) {
    checksumBytes.push(Number((checksumVal >> BigInt(i * 8)) & 0xffn));
  }
  const checksum5bit = conv8to5(checksumBytes);

  // Encode: prefix + ":" + fivebitPayload + checksum5bit
  let addr = prefix + ":";
  for (const d of [...fivebitPayload, ...checksum5bit]) {
    addr += CHARSET[d];
  }
  return addr;
}

// ── Main ─────────────────────────────────────────────────────────────

function main() {
  const envPath = path.join(__dirname, ".env");

  // Check if .env already has a key
  let privateKeyHex;
  if (fs.existsSync(envPath)) {
    const envContent = fs.readFileSync(envPath, "utf-8");
    const match = envContent.match(/^PRIVATE_KEY=0x([0-9a-fA-F]{64})$/m);
    if (match) {
      privateKeyHex = match[1];
      console.log("Using existing key from .env\n");
    }
  }

  if (!privateKeyHex) {
    // Generate fresh key
    const wallet = ethers.Wallet.createRandom();
    privateKeyHex = wallet.privateKey.slice(2);

    // Write to .env
    const envContent = `# Generated by generate-wallet.js\n# NEVER commit this file\nPRIVATE_KEY=0x${privateKeyHex}\n`;
    fs.writeFileSync(envPath, envContent, { mode: 0o600 });
    console.log("Generated new key, saved to .env (chmod 600)\n");
  }

  // Ensure .gitignore
  const gitignorePath = path.join(__dirname, ".gitignore");
  let gitignore = "";
  if (fs.existsSync(gitignorePath)) {
    gitignore = fs.readFileSync(gitignorePath, "utf-8");
  }
  if (!gitignore.includes(".env")) {
    fs.appendFileSync(gitignorePath, "\n.env\nnode_modules/\n");
    console.log("Added .env to .gitignore\n");
  }

  // ── EVM address ──
  const evmWallet = new ethers.Wallet("0x" + privateKeyHex);
  const evmAddress = evmWallet.address;

  // ── Kaspa address ──
  const signingKey = new ethers.SigningKey("0x" + privateKeyHex);
  const compressedPubkey = signingKey.compressedPublicKey; // 0x02... or 0x03...
  const xOnlyHex = compressedPubkey.slice(4); // drop 0x02/0x03 prefix
  const xOnlyBytes = Buffer.from(xOnlyHex, "hex");

  // Kaspa PubKey address: version 0x00 + 32-byte x-only pubkey
  const kaspaAddress = kaspaAddressEncode("kaspa", 0x00, [...xOnlyBytes]);

  // ── Output ──
  console.log("=== Unified Wallet ===");
  console.log("");
  console.log("EVM Address (Ethereum, Base, Igra):");
  console.log(`  ${evmAddress}`);
  console.log("");
  console.log("Kaspa Address (L1):");
  console.log(`  ${kaspaAddress}`);
  console.log("");
  console.log("--- Fund instructions ---");
  console.log(`  Base:  Send USDC to ${evmAddress}`);
  console.log(`  Kaspa: Send KAS to ${kaspaAddress}`);
  console.log("");
  console.log("Same key on .env works for all chains.");

  // Cross-check with Rust binary if available
  const ENTRY_BIN = "/Users/emdin/Projects/igra/tmp/igra-foundry/target/release/igra_entry_tx";
  try {
    const { execSync } = require("child_process");
    if (require("fs").existsSync(ENTRY_BIN)) {
      const stderr = (() => {
        try {
          execSync(
            `${ENTRY_BIN} --preset mainnet --private-key ${privateKeyHex} --recipient ${evmAddress} --amount 10 --dry-run`,
            { encoding: "utf-8", timeout: 30000, stdio: ["pipe", "pipe", "pipe"] }
          );
        } catch (e) { return e.stderr || ""; }
        return "";
      })();
      const match = stderr.match(/kaspa sender:\s+(kaspa:\S+)/);
      if (match) {
        const rustAddr = match[1];
        if (rustAddr === kaspaAddress) {
          console.log("\nKaspa address verified against Rust binary.");
        } else {
          console.log("\nWARNING: Kaspa address mismatch!");
          console.log("  JS:   " + kaspaAddress);
          console.log("  Rust: " + rustAddr + "  <-- USE THIS ONE");
        }
      }
    }
  } catch {}
}

main();
