/**
 * KAS ↔ USDC Interactive Demo
 *
 * Clean, interactive, commercial-quality demo for selling KAS for USDC
 * and buying KAS with USDC. Full progress display.
 *
 * Usage:
 *   node swap-demo.js sell    — Sell KAS for USDC on Base
 *   node swap-demo.js buy     — Buy KAS with USDC from Base
 */

const { ethers } = require("ethers");
const { execSync } = require("child_process");
const readline = require("readline");
const fs = require("fs");
const path = require("path");
require("dotenv").config();

// ── Config ───────────────────────────────────────────────────────────

const IGRA_RPC = "https://rpc.igralabs.com:8545";
const BASE_RPC = "https://mainnet.base.org";
const GP = 1_100_000_000_000n;
const ENTRY_BIN = "/Users/emdin/Projects/igra/tmp/igra-foundry/target/release/igra_entry_tx";

const C = {
  USDC_BASE: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
  WARP_BASE: "0x84e1dF3553B16452AeD7060A4266E4E434f418cC",
  USDC_IGRA: "0xA5b8BF902b2844dA17d4506cc827F7F1681735E7",
  ROUTER:    "0xA5B0946D31aD2d251e0fe2dfEA8808BFd475e607",
  WIKAS:     "0x17Ec7E1768c813E2a3a9b0f94A35605CA520C242",
  POOL:      "0x7826f5421c324590b1c21d22231c48ad059cbe45",
  KASBRIDGE: "0xb82c5524c5b5c055efb2F8f4AbCcE3173c504f2d",
};

// ── Display ──────────────────────────────────────────────────────────

const DIM = "\x1b[2m", RST = "\x1b[0m", GRN = "\x1b[32m", YEL = "\x1b[33m";
const CYN = "\x1b[36m", BLD = "\x1b[1m", RED = "\x1b[31m";

let t0;
function el() { return ((Date.now() - t0) / 1000).toFixed(1) + "s"; }

function progress(step, total, label, detail) {
  const bar = Array.from({ length: total }, (_, i) => i < step ? "█" : "░").join("");
  const pct = Math.round((step / total) * 100);
  process.stdout.write(`\r  ${CYN}${bar}${RST} ${pct}% ${DIM}[${el()}]${RST} ${label}  ${detail || ""}          `);
}

function done(step, total, label, detail) {
  const bar = Array.from({ length: total }, (_, i) => i < step ? "█" : "░").join("");
  const pct = Math.round((step / total) * 100);
  console.log(`\r  ${GRN}${bar}${RST} ${pct}% ${DIM}[${el()}]${RST} ${GRN}${label}${RST}  ${detail || ""}          `);
}

function header(text) {
  console.log(`\n${BLD}${CYN}${"═".repeat(60)}${RST}`);
  console.log(`${BLD}  ${text}${RST}`);
  console.log(`${CYN}${"═".repeat(60)}${RST}\n`);
}

function info(label, value) { console.log(`  ${DIM}${label}:${RST} ${value}`); }

function amtOut(a, rIn, rOut) { const f = a * 997n; return (f * rOut) / (rIn * 1000n + f); }

// ── Interactive prompts ──────────────────────────────────────────────

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

function ask(question, defaultVal) {
  const suffix = defaultVal ? ` ${DIM}(${defaultVal})${RST}: ` : ": ";
  return new Promise(resolve => {
    rl.question(`  ${question}${suffix}`, answer => {
      resolve(answer.trim() || defaultVal || "");
    });
  });
}

async function confirm(question) {
  const answer = await ask(question, "Y");
  return answer.toLowerCase() !== "n";
}

// ── Wallet setup ─────────────────────────────────────────────────────

async function setupWallet() {
  header("WALLET SETUP");

  const envPath = path.join(__dirname, ".env");
  let privateKeyHex;

  if (fs.existsSync(envPath)) {
    const envContent = fs.readFileSync(envPath, "utf-8");
    const match = envContent.match(/^PRIVATE_KEY=0x([0-9a-fA-F]{64})$/m);
    if (match) {
      privateKeyHex = match[1];
      const wallet = new ethers.Wallet("0x" + privateKeyHex);
      console.log(`  Found existing wallet: ${CYN}${wallet.address}${RST}`);
      if (await confirm("Reuse this wallet? (Y/n)")) {
        console.log("");
        return privateKeyHex;
      }
    }
  }

  // Generate new
  console.log(`  Generating new wallet...`);
  const wallet = ethers.Wallet.createRandom();
  privateKeyHex = wallet.privateKey.slice(2);
  const envContent = `# Generated by swap-demo.js\n# NEVER commit this file\nPRIVATE_KEY=0x${privateKeyHex}\n`;
  fs.writeFileSync(envPath, envContent, { mode: 0o600 });

  // Ensure .gitignore
  const gitignorePath = path.join(__dirname, ".gitignore");
  let gitignore = fs.existsSync(gitignorePath) ? fs.readFileSync(gitignorePath, "utf-8") : "";
  if (!gitignore.includes(".env")) fs.appendFileSync(gitignorePath, "\n.env\nnode_modules/\n");

  console.log(`  ${GRN}New wallet created${RST} (key saved to .env)\n`);
  return privateKeyHex;
}

function deriveAddresses(privateKeyHex) {
  const wallet = new ethers.Wallet("0x" + privateKeyHex);
  const evmAddress = wallet.address;

  // Kaspa address — derive from Rust binary (authoritative)
  let kaspaAddress = "";
  try {
    const stderr = (() => {
      try {
        execSync(`${ENTRY_BIN} --preset mainnet --private-key ${privateKeyHex} --recipient ${evmAddress} --amount 10 --dry-run`,
          { encoding: "utf-8", timeout: 60000, stdio: ["pipe", "pipe", "pipe"] });
      } catch (e) { return e.stderr || ""; }
      return "";
    })();
    const match = stderr.match(/kaspa sender:\s+(kaspa:\S+)/);
    if (match) kaspaAddress = match[1];
  } catch {}

  return { evmAddress, kaspaAddress };
}

// ── SELL FLOW ────────────────────────────────────────────────────────

async function sellFlow(privateKeyHex) {
  const { evmAddress, kaspaAddress } = deriveAddresses(privateKeyHex);

  header("SELL KAS FOR USDC");

  info("Your Kaspa address", kaspaAddress);
  info("Your EVM address", evmAddress);
  console.log("");

  // Ask amount
  const amountStr = await ask("How much KAS to sell?");
  const amountKas = parseFloat(amountStr);
  if (!amountKas || amountKas <= 0) { console.log(`  ${RED}Invalid amount${RST}`); return; }

  // Ask delivery address
  const deliveryAddr = await ask("Deliver USDC to which Base address?", evmAddress);
  if (!deliveryAddr.match(/^0x[0-9a-fA-F]{40}$/)) { console.log(`  ${RED}Invalid address${RST}`); return; }

  // Gas budget: need ~1.5 iKAS for Igra txs. Entry extra to cover.
  const entryAmount = amountKas + 2; // 2 extra KAS for gas on Igra

  console.log("");
  header("SELL ORDER SUMMARY");
  info("Sell", `${amountKas} KAS`);
  info("Entry", `${entryAmount} KAS (includes 2 KAS for Igra gas)`);
  info("Route", "KAS → Igra → USDC → Hyperlane → Base");
  info("USDC delivery", deliveryAddr);
  console.log("");

  if (!await confirm("Proceed? (Y/n)")) { console.log("  Cancelled."); return; }

  // Check KAS balance
  console.log("");
  info("Checking Kaspa L1 balance", "...");
  let kasBalance = 0;
  try {
    const stderr = (() => {
      try {
        execSync(`${ENTRY_BIN} --preset mainnet --private-key ${privateKeyHex} --recipient ${evmAddress} --amount 10 --dry-run`,
          { encoding: "utf-8", timeout: 60000, stdio: ["pipe", "pipe", "pipe"] });
      } catch (e) { return e.stderr || ""; }
      return "";
    })();
    const match = stderr.match(/\(([\d.]+)\s+KAS\)/);
    if (match) kasBalance = parseFloat(match[1]);
  } catch {}
  info("Kaspa L1 balance", `${kasBalance} KAS`);

  if (kasBalance < entryAmount) {
    console.log(`\n  ${YEL}Insufficient KAS. Need ${entryAmount} KAS, have ${kasBalance} KAS.${RST}`);
    console.log(`  ${YEL}Send ${(entryAmount - kasBalance).toFixed(1)} more KAS to: ${kaspaAddress}${RST}`);
    console.log(`\n  Waiting for KAS to arrive (polling every 10s)...`);
    while (true) {
      await new Promise(r => setTimeout(r, 10000));
      try {
        const stderr = (() => {
          try {
            execSync(`${ENTRY_BIN} --preset mainnet --private-key ${privateKeyHex} --recipient ${evmAddress} --amount 10 --dry-run`,
              { encoding: "utf-8", timeout: 60000, stdio: ["pipe", "pipe", "pipe"] });
          } catch (e) { return e.stderr || ""; }
          return "";
        })();
        const match = stderr.match(/\(([\d.]+)\s+KAS\)/);
        if (match) kasBalance = parseFloat(match[1]);
        if (kasBalance >= entryAmount) {
          console.log(`  ${GRN}KAS received: ${kasBalance} KAS${RST}`);
          break;
        }
      } catch {}
      process.stdout.write(".");
    }
  }

  // ── Execute ──
  header("EXECUTING SELL");
  t0 = Date.now();
  const S = 7;

  const provider = new ethers.JsonRpcProvider(IGRA_RPC);
  const wallet = new ethers.Wallet("0x" + privateKeyHex, provider);

  // Step 1: IGRA entry
  progress(0, S, "Submitting IGRA entry...");
  try {
    execSync(`${ENTRY_BIN} --preset mainnet --private-key ${privateKeyHex} --recipient ${evmAddress} --amount ${entryAmount}`,
      { encoding: "utf-8", timeout: 60000, stdio: ["pipe", "pipe", "pipe"] });
  } catch (e) {
    if (!(e.stdout || "").toString().includes("kaspa_tx_id")) throw new Error("Entry failed");
  }
  done(1, S, "Entry submitted", `${entryAmount} KAS`);

  // Step 2: Wait for iKAS
  progress(1, S, "Waiting for iKAS on Igra...");
  const ikBefore = await provider.getBalance(evmAddress);
  while (true) {
    const cur = await provider.getBalance(evmAddress);
    if (cur > ikBefore) { done(2, S, "iKAS arrived", `+${ethers.formatEther(cur - ikBefore)} iKAS`); break; }
    await new Promise(r => setTimeout(r, 3000));
  }

  // Step 3: Wrap
  progress(2, S, "Wrapping iKAS → WiKAS...");
  const ikTotal = await provider.getBalance(evmAddress);
  const gasReserve = ethers.parseEther("1.5");
  const wrapAmt = ikTotal - gasReserve;
  const wikas = new ethers.Contract(C.WIKAS,
    ["function deposit() payable", "function approve(address,uint256) returns (bool)", "function balanceOf(address) view returns (uint256)"], wallet);
  await (await wikas.deposit({ value: wrapAmt, gasPrice: GP, type: 0 })).wait();
  const wBal = await wikas.balanceOf(evmAddress);
  done(3, S, "Wrapped", `${ethers.formatEther(wBal).slice(0, 8)} WiKAS`);

  // Step 4: Swap
  progress(3, S, "Swapping WiKAS → USDC...");
  const pool = new ethers.Contract(C.POOL, ["function getReserves() view returns (uint112,uint112,uint32)"], provider);
  const [r0, r1] = await pool.getReserves();
  const expUsdc = amtOut(wBal, r0, r1);
  await (await wikas.approve(C.ROUTER, wBal, { gasPrice: GP, type: 0 })).wait();
  const blk = await provider.getBlock("latest");
  await (await new ethers.Contract(C.ROUTER,
    ["function swapExactTokensForTokens(uint,uint,address[],address,uint) returns (uint[])"], wallet)
    .swapExactTokensForTokens(wBal, (expUsdc * 97n) / 100n, [C.WIKAS, C.USDC_IGRA], evmAddress, blk.timestamp + 600,
      { gasPrice: GP, gasLimit: 300_000n, type: 0 }
    )).wait();
  const usdcBal = await new ethers.Contract(C.USDC_IGRA, ["function balanceOf(address) view returns (uint256)"], provider).balanceOf(evmAddress);
  done(4, S, "Swapped", `${ethers.formatUnits(usdcBal, 6)} USDC`);

  // Step 5: Approve for bridge
  progress(4, S, "Approving USDC for Hyperlane bridge...");
  const usdcWarp = new ethers.Contract(C.USDC_IGRA,
    ["function approve(address,uint256) returns (bool)", "function transferRemote(uint32,bytes32,uint256) payable returns (bytes32)",
     "function quoteGasPayment(uint32) view returns (uint256)", "function balanceOf(address) view returns (uint256)"], wallet);
  await (await usdcWarp.approve(C.USDC_IGRA, ethers.MaxUint256, { gasPrice: GP, type: 0 })).wait();
  done(5, S, "Approved", "");

  // Step 6: Bridge
  progress(5, S, "Bridging USDC to Base...");
  const gasPayment = await usdcWarp.quoteGasPayment(8453);
  const bridgeAmt = usdcBal * 999n / 1000n; // ~0.1% Hyperlane fee
  const recipient = ethers.zeroPadValue(deliveryAddr, 32);
  await (await usdcWarp.transferRemote(8453, recipient, bridgeAmt,
    { value: gasPayment, gasPrice: GP, gasLimit: 350_000n, type: 0 }
  )).wait();
  done(6, S, "Bridge tx confirmed", `${ethers.formatUnits(bridgeAmt, 6)} USDC`);

  // Step 7: Wait for Base
  progress(6, S, "Waiting for USDC on Base...");
  const baseProvider = new ethers.JsonRpcProvider(BASE_RPC);
  const usdcBase = new ethers.Contract(C.USDC_BASE, ["function balanceOf(address) view returns (uint256)"], baseProvider);
  const baseBefore = await usdcBase.balanceOf(deliveryAddr);
  while (true) {
    const now = await usdcBase.balanceOf(deliveryAddr);
    if (now > baseBefore) {
      const received = now - baseBefore;
      done(7, S, "USDC delivered!", `+${ethers.formatUnits(received, 6)} USDC`);
      break;
    }
    await new Promise(r => setTimeout(r, 10000));
  }

  // Report
  header("SELL COMPLETE");
  info("Sold", `${amountKas} KAS`);
  info("Delivered", `${ethers.formatUnits(bridgeAmt, 6)} USDC to ${deliveryAddr} on Base`);
  info("Time", el());
}

// ── BUY FLOW ─────────────────────────────────────────────────────────

async function buyFlow(privateKeyHex) {
  const { evmAddress, kaspaAddress } = deriveAddresses(privateKeyHex);

  header("BUY KAS WITH USDC");

  info("Your EVM address", evmAddress);
  info("Your Kaspa address", kaspaAddress);
  console.log("");

  // Ask amount
  const amountStr = await ask("How much USDC to spend?");
  const amountUsdc = parseFloat(amountStr);
  if (!amountUsdc || amountUsdc <= 0) { console.log(`  ${RED}Invalid amount${RST}`); return; }

  // Ask delivery address
  const deliveryAddr = await ask("Deliver KAS to which Kaspa address?", kaspaAddress);
  if (!deliveryAddr.startsWith("kaspa:")) { console.log(`  ${RED}Invalid Kaspa address${RST}`); return; }

  // Check USDC on Base
  const baseProvider = new ethers.JsonRpcProvider(BASE_RPC);
  const usdcBase = new ethers.Contract(C.USDC_BASE, ["function balanceOf(address) view returns (uint256)"], baseProvider);
  const usdcBal = await usdcBase.balanceOf(evmAddress);
  const usdcAmount = BigInt(Math.floor(amountUsdc * 1e6));

  // Check ETH for Hyperlane gas
  const ethBal = await baseProvider.getBalance(evmAddress);
  const warp = new ethers.Contract(C.WARP_BASE, ["function quoteGasPayment(uint32) view returns (uint256)"], baseProvider);
  const hypGas = await warp.quoteGasPayment(38833);

  // Check iKAS on Igra
  const igraProvider = new ethers.JsonRpcProvider(IGRA_RPC);
  const ikasBal = await igraProvider.getBalance(evmAddress);

  console.log("");
  header("BUY ORDER SUMMARY");
  info("Spend", `${amountUsdc} USDC on Base`);
  info("Route", "USDC → Hyperlane → Igra → WiKAS → iKAS → KasBridge → KAS");
  info("KAS delivery", deliveryAddr);
  info("KasBridge fee", "10 iKAS flat floor");
  console.log("");
  info("Base USDC balance", ethers.formatUnits(usdcBal, 6));
  info("Base ETH balance", ethers.formatEther(ethBal));
  info("Igra iKAS balance", ethers.formatEther(ikasBal));
  console.log("");

  if (usdcBal < usdcAmount) {
    console.log(`  ${YEL}Insufficient USDC. Need ${amountUsdc}, have ${ethers.formatUnits(usdcBal, 6)}.${RST}`);
    console.log(`  ${YEL}Send ${amountUsdc} USDC to: ${evmAddress} on Base${RST}`);
    console.log(`\n  Waiting for USDC (polling every 10s)...`);
    while (true) {
      await new Promise(r => setTimeout(r, 10000));
      const now = await usdcBase.balanceOf(evmAddress);
      if (now >= usdcAmount) { console.log(`  ${GRN}USDC received: ${ethers.formatUnits(now, 6)}${RST}`); break; }
      process.stdout.write(".");
    }
  }

  if (ethBal < hypGas + 100_000n * 100_000n) {
    console.log(`  ${YEL}Need ~${ethers.formatEther(hypGas)} ETH on Base for Hyperlane gas.${RST}`);
    console.log(`  ${YEL}Send ETH to: ${evmAddress} on Base${RST}`);
    console.log(`\n  Waiting for ETH...`);
    while (true) {
      await new Promise(r => setTimeout(r, 10000));
      const now = await baseProvider.getBalance(evmAddress);
      if (now >= hypGas + 100_000n * 100_000n) { console.log(`  ${GRN}ETH received${RST}`); break; }
      process.stdout.write(".");
    }
  }

  if (ikasBal < ethers.parseEther("0.6")) {
    console.log(`  ${YEL}Need ~0.6 iKAS on Igra for gas. Current: ${ethers.formatEther(ikasBal)}${RST}`);
    console.log(`  ${YEL}Options: faucet (https://faucet.igralabs.com) or IGRA entry from Kaspa L1${RST}`);
    console.log(`\n  Waiting for iKAS on Igra...`);
    while (true) {
      await new Promise(r => setTimeout(r, 10000));
      const now = await igraProvider.getBalance(evmAddress);
      if (now >= ethers.parseEther("0.5")) { console.log(`  ${GRN}iKAS ready: ${ethers.formatEther(now)}${RST}`); break; }
      process.stdout.write(".");
    }
  }

  if (!await confirm("Proceed? (Y/n)")) { console.log("  Cancelled."); return; }

  // ── Execute ──
  header("EXECUTING BUY");
  t0 = Date.now();
  const S = 8;
  const igraWallet = new ethers.Wallet("0x" + privateKeyHex, igraProvider);
  const baseWallet = new ethers.Wallet("0x" + privateKeyHex, baseProvider);

  // Step 1: Bridge USDC to Igra
  progress(0, S, "Bridging USDC to Igra via Hyperlane...");
  const warpC = new ethers.Contract(C.WARP_BASE,
    ["function transferRemote(uint32,bytes32,uint256) payable returns (bytes32)", "function quoteGasPayment(uint32) view returns (uint256)"], baseWallet);
  const gp = await warpC.quoteGasPayment(38833);
  const actualUsdc = await new ethers.Contract(C.USDC_BASE, ["function balanceOf(address) view returns (uint256)"], baseProvider).balanceOf(evmAddress);
  const bridgeUsdc = actualUsdc < usdcAmount ? actualUsdc : usdcAmount;
  // Approve
  await (await new ethers.Contract(C.USDC_BASE, ["function approve(address,uint256) returns (bool)"], baseWallet)
    .approve(C.WARP_BASE, ethers.MaxUint256)).wait();
  await (await warpC.transferRemote(38833, ethers.zeroPadValue(evmAddress, 32), bridgeUsdc, { value: gp })).wait();
  done(1, S, "Bridge tx confirmed", "");

  // Step 2: Wait for USDC on Igra
  progress(1, S, "Waiting for USDC on Igra...");
  const usdcIgra = new ethers.Contract(C.USDC_IGRA, ["function balanceOf(address) view returns (uint256)"], igraProvider);
  const igraBefore = await usdcIgra.balanceOf(evmAddress);
  while (true) {
    const b = await usdcIgra.balanceOf(evmAddress);
    if (b > igraBefore) { done(2, S, "USDC on Igra", `${ethers.formatUnits(b, 6)}`); break; }
    await new Promise(r => setTimeout(r, 5000));
  }

  // Step 3: Swap USDC → WiKAS
  progress(2, S, "Swapping USDC → WiKAS...");
  const igraUsdcBal = await usdcIgra.balanceOf(evmAddress);
  await (await new ethers.Contract(C.USDC_IGRA, ["function approve(address,uint256) returns (bool)"], igraWallet)
    .approve(C.ROUTER, igraUsdcBal, { gasPrice: GP, type: 0 })).wait();
  const pool = new ethers.Contract(C.POOL, ["function getReserves() view returns (uint112,uint112,uint32)"], igraProvider);
  const [r0, r1] = await pool.getReserves();
  const blk = await igraProvider.getBlock("latest");
  await (await new ethers.Contract(C.ROUTER,
    ["function swapExactTokensForTokens(uint,uint,address[],address,uint) returns (uint[])"], igraWallet)
    .swapExactTokensForTokens(igraUsdcBal, 0n, [C.USDC_IGRA, C.WIKAS], evmAddress, blk.timestamp + 600,
      { gasPrice: GP, gasLimit: 300_000n, type: 0 }
    )).wait();
  const wBal = await new ethers.Contract(C.WIKAS, ["function balanceOf(address) view returns (uint256)"], igraProvider).balanceOf(evmAddress);
  done(3, S, "Swapped", `${ethers.formatEther(wBal).slice(0, 8)} WiKAS`);

  // Step 4: Unwrap WiKAS → iKAS
  progress(3, S, "Unwrapping WiKAS → iKAS...");
  await (await new ethers.Contract(C.WIKAS, ["function withdraw(uint256)"], igraWallet)
    .withdraw(wBal, { gasPrice: GP, type: 0 })).wait();
  const ikBal = await igraProvider.getBalance(evmAddress);
  done(4, S, "Unwrapped", `${ethers.formatEther(ikBal).slice(0, 8)} iKAS`);

  // Step 5: Lock for exit
  progress(4, S, "Locking iKAS for KasBridge exit...");
  const kb = new ethers.Contract(C.KASBRIDGE,
    ["function lockForExit(bytes) payable", "function exits(uint256) view returns (address,uint256,uint256,uint256,bytes,uint256,bool,bool,bool,bytes32)",
     "function exitCounter() view returns (uint256)", "function getCurrentFee(uint256) view returns (uint256)"], igraWallet);
  const gasLim = 350_000n;
  const exitAmt = ikBal - gasLim * GP;
  const fee = await kb.getCurrentFee(exitAmt);
  const net = exitAmt - fee;

  if (net < ethers.parseEther("10")) {
    done(5, S, "Below KasBridge minimum", `${ethers.formatEther(net).slice(0, 8)} net < 10 iKAS`);
    console.log(`\n  ${YEL}Net amount after 10 iKAS fee is too low for KasBridge exit.${RST}`);
    console.log(`  ${YEL}Need to spend more USDC (>$0.70) to get enough iKAS.${RST}`);
    header("PARTIAL RESULT");
    info("iKAS on Igra", ethers.formatEther(ikBal));
    return;
  }

  const ctr = await kb.exitCounter();
  await (await kb.lockForExit(ethers.toUtf8Bytes(deliveryAddr),
    { value: exitAmt, gasPrice: GP, gasLimit: gasLim, type: 0 }
  )).wait();
  done(5, S, "Locked", `Exit #${ctr} | net: ${ethers.formatEther(net).slice(0, 8)} KAS | fee: ${ethers.formatEther(fee)}`);

  // Step 6-8: Wait for L1 release
  let acked = false;
  progress(5, S, "Waiting for relayer acknowledgment...");
  for (let i = 0; i < 40; i++) {
    await new Promise(r => setTimeout(r, 30000));
    const e = await kb.exits(ctr);
    if (e[7] && e[9] !== ethers.ZeroHash) {
      if (!acked) done(6, S, "Acknowledged", "");
      done(7, S, "FROST signed", "");
      done(8, S, "KAS released!", `${ethers.formatEther(e[3]).slice(0, 8)} KAS`);

      header("BUY COMPLETE");
      info("Spent", `${amountUsdc} USDC on Base`);
      info("Delivered", `${ethers.formatEther(e[3])} KAS to ${deliveryAddr}`);
      info("Kaspa TX", e[9]);
      info("KasBridge fee", `${ethers.formatEther(fee)} iKAS`);
      info("Time", el());
      return;
    }
    if (e[6] && !acked) {
      done(6, S, "Acknowledged by relayers", "");
      progress(6, S, "FROST threshold signing...");
      acked = true;
    }
  }
  console.log(`\n  ${YEL}L1 release pending. Exit #${ctr} — check later.${RST}`);
}

// ── MAIN ─────────────────────────────────────────────────────────────

async function main() {
  const mode = process.argv[2];
  if (!mode || !["sell", "buy"].includes(mode)) {
    console.log(`\n  ${BLD}KAS ↔ USDC Swap Demo${RST}`);
    console.log(`\n  Usage:`);
    console.log(`    node swap-demo.js sell    ${DIM}— Sell KAS for USDC on Base${RST}`);
    console.log(`    node swap-demo.js buy     ${DIM}— Buy KAS with USDC from Base${RST}\n`);
    process.exit(0);
  }

  const privateKeyHex = await setupWallet();
  const { evmAddress, kaspaAddress } = deriveAddresses(privateKeyHex);

  console.log(`  ${DIM}EVM:${RST}   ${evmAddress}`);
  console.log(`  ${DIM}Kaspa:${RST} ${kaspaAddress}`);

  if (mode === "sell") {
    await sellFlow(privateKeyHex);
  } else {
    await buyFlow(privateKeyHex);
  }

  rl.close();
}

main().catch(e => {
  console.error(`\n  ${RED}ERROR: ${e.shortMessage || e.message}${RST}`);
  rl.close();
  process.exit(1);
});
